### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_20_hotspot#41]
Major:
- [x] Add map selection of country, #43 
- [x] Log scaling or get, #43 
- [x] #49
    - [x] E.g. side bar and card in side bar #50 

Minor:
- [x] Legends? #43 
- [x] Country label #43 
- [x] Total temp change should be average #43 
- [ ] Look into whats going on with temp change data
- [x] Clearer separation between columns #50 
- [ ] Maybe background on title?
- [x] Shorten tag line or more whitespace #50

**Comment by farrandi** [comment]
use `dbc.collapse()` for the description under the header (also see Joel's example on "learn more") click

**Comment by farrandi** [comment]
Set `fluid=True` for having containers span the whole window

**Comment by monazhu** [comment]
**Response to temperature change data:**
- We looked at how the data was being aggregated in the output and it is in fact taking the average temperature change, not total. The values do seem small, but considering a 1 degree change in temperature is actually quite a lot (especially year after year change), these values do seem to make sense

**Background colour on title:**
- We tested a few different outputs and colour combinations and found the one that worked best was colouring the background of the widget (to make it stand out more) but leaving the background on title uncoloured. When only the background on the title container was coloured, it didn't seem to offer usability gains in terms of delineating the rest of the dashboard; when both the background and widget were coloured, the dashboard looked too busy.
