### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_20_hotspot#65]
Implement two major and two minor

Major:

- [x] Figure out how to scale up map and have the layout so that the two charts under the map are the same width overall as the map #64 
    - [x] Maybe remove Antarctica? #64 
- [x] Either additional output or a toggle to change between per capita and overall. Either local for bach chart, or globa lin side bar to affect all charts. #79 

Minor:

- [x] Somewhere indicate that the temp change is an average per country #78 
- [x] Set default tool as box select #64 
- [x] Make sure x-axis labels in bottom left bar plot #64 
- [x] #84
